services:
  comfyui-rest-api:
    command: bash -c "python ComfyUI/main.py & python src/rp_handler.py"
    container_name: comfyui-rest-api
    image: comfyui-rest-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8188:8188
    # volumes:
    #   - ./models/checkpoints:/usr/app/comfyui-rest-api/ComfyUI/models/checkpoints
    #   - ./src:/usr/app/comfyui-rest-api/src
